/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of Mytest3.xs. Do not edit this file, edit Mytest3.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Mytest3.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "mylib/mylib.h"

#include "const-c.inc"

#line 21 "Mytest3.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 73 "Mytest3.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Mytest3.xs' */


XS(XS_Mytest3_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest3_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 102 "Mytest3.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Mytest3 macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Mytest3 macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Mytest3 macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 179 "Mytest3.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Mytest3.xs' from 'const-xs.inc' */


XS(XS_Mytest3_do_path); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest3_do_path)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 7)
       croak_xs_usage(cv,  "rawMap, width, height, startX, startY, endX, endY");
    {
	SV *	rawMap = ST(0);
	unsigned long	width = (unsigned long)SvUV(ST(1));
	unsigned long	height = (unsigned long)SvUV(ST(2));
	unsigned long	startX = (unsigned long)SvUV(ST(3));
	unsigned long	startY = (unsigned long)SvUV(ST(4));
	unsigned long	endX = (unsigned long)SvUV(ST(5));
	unsigned long	endY = (unsigned long)SvUV(ST(6));
	int	RETVAL;
	dXSTARG;
#line 26 "Mytest3.xs"
		STRLEN len;
		unsigned char *c_rawMap, *data;

#line 213 "Mytest3.c"
#line 30 "Mytest3.xs"
		if (!SvOK (rawMap))
			XSRETURN_UNDEF;

		c_rawMap = (unsigned char *) SvPV (rawMap, len);
		if ((int) len != width * height)
			XSRETURN_UNDEF;

		New (0, data, len, unsigned char);
		Copy (c_rawMap, data, len, unsigned char);

		Map* currentMap = GenerateMap(data, width, height);

		main(currentMap, startX, startY, endX, endY);
		RETVAL = 1;

#line 230 "Mytest3.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Mytest3_makeDistMap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Mytest3_makeDistMap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "rawMap, width, height");
    {
	SV *	rawMap = ST(0);
	unsigned long	width = (unsigned long)SvUV(ST(1));
	unsigned long	height = (unsigned long)SvUV(ST(2));
	SV *	RETVAL;
#line 56 "Mytest3.xs"
		STRLEN len;
		unsigned char *c_rawMap, *data;

#line 256 "Mytest3.c"
#line 60 "Mytest3.xs"
		if (!SvOK (rawMap))
			XSRETURN_UNDEF;

		c_rawMap = (unsigned char *) SvPV (rawMap, len);
		if ((int) len != width * height)
			XSRETURN_UNDEF;

		New (0, data, len, unsigned char);
		Copy (c_rawMap, data, len, unsigned char);

		unsigned char *result;

		result = printinfo(data, width, height);

		RETVAL = newSVpv ((const char *) result, (width * height));

#line 274 "Mytest3.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mytest3); /* prototype to pass -Wmissing-prototypes */
XS(boot_Mytest3)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Mytest3::constant", XS_Mytest3_constant, file);
        newXS("Mytest3::do_path", XS_Mytest3_do_path, file);
        newXS("Mytest3::makeDistMap", XS_Mytest3_makeDistMap, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

